// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the Family Care Scheduler app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1lnRD5V6yyo-eXOYlBUOyZOmMZ0DCNC0',
    appId: '1:388117547421:android:e918699aee99efe9830774',
    messagingSenderId: '388117547421',
    projectId: 'family-care-scheduler-dev',
    storageBucket: 'family-care-scheduler-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1lnRD5V6yyo-eXOYlBUOyZOmMZ0DCNC0',
    appId: '1:388117547421:ios:8b2b679003400955830774',
    messagingSenderId: '388117547421',
    projectId: 'family-care-scheduler-dev',
    storageBucket: 'family-care-scheduler-dev.firebasestorage.app',
    iosBundleId: 'com.familycare.scheduler.familyCareScheduler',
  );
}
